# Generated by Django 5.0.1 on 2024-01-26 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact_info_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
