# Generated by Django 5.0.1 on 2024-06-12 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_person_first_name_person_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
    ]
