# Generated by Django 5.0.1 on 2024-06-17 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_person_first_name_remove_person_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('app', models.CharField(max_length=8)),
                ('disease', models.CharField(max_length=20, null=True)),
                ('result', models.CharField(max_length=10)),
                ('probability', models.FloatField(null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
        ),
    ]
