# Generated by Django 5.0.1 on 2024-06-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
